### ISSUE TITLE
compiling issue using mxnet configuration

### ISSUE THREAD

**Issue by kaishijeng** [OAID/face-demo#1]
I have configured mxnet on and caffe off in config.mk:
CONFIG_CAFFE_MTCNN=n
CONFIG_TENSORFLOW_MTCNN=n
CONFIG_MXNET_MTCNN=y

But compilation needs header file from caffe and generate error below. Can you check?

g++ -std=c++11 -I/home/firefly/2TB/src/firefly/mxnetOnACL/include -I/home/firefly/2TB/src/firefly/mxnetOnACL/dmlc-core/include -I/home/firefly/2TB/src/firefly/mxnetOnACL/nnvm/include -Wno-sign-compare -Wall -g     -I./include   -DMODEL_DIR=\"/home/firefly/2TB/src/firefly/face-demo/models\" -I/usr/local/include/opencv -I/usr/local/include  -c extract/lightened_cnn.cpp -o build/extract/lightened_cnn.o
In file included from extract/lightened_cnn.cpp:2:0:
./include/lightened_cnn.hpp:4:27: fatal error: caffe/caffe.hpp: No such file or directory

**Comment by cyberfire** [comment]
@kaishijeng 

As the face recognition algorithm,  lightened CNN, is a caffe model, so that, caffe is necessary.

Thanks,
Haitao

**Comment by kaishijeng** [comment]
Hi, Haitao,

   Can I use caffeOnACL instead of regular caffe?
If yes, what should I change in the Makefile to make compilation works?

Thanks,

**Comment by kaishijeng** [comment]
Hi, Haitao

I add caffeOnACL/include to  include path of Makefile and got the following error:
/home/firefly/2TB/src/firefly/caffeOnACL/include/caffe/util/device_alternate.hpp:38:23: fatal error: cublas_v2.h: No such file or directory

Do I need to use regular caffe instead of caffOnACL?

Thanks,

**Comment by cyberfire** [comment]
@kaishijeng 

Did you compile it correctly with original Caffe?
I do not think there is any additional thing needs to do for CaffeOnACL in compiling phase.
While in the linking phase, you needs to add the ACL libraries.

Thanks,

Haitao

**Comment by kaishijeng** [comment]
After I modify Makefile to include libcaffe.so to the link library, I still
go the following error:

/usr/bin/ld: ./build/extract/lightened_cnn.o: undefined reference to symbol
'_ZN6google4base21CheckOpMessageBuilder7ForVar2Ev'
//usr/lib/aarch64-linux-gnu/libglog.so.0: error adding symbols: DSO missing
from command line
collect2: error: ld returned 1 exit status
Makefile:83: recipe for target 'build/bin/camera' failed

Not sure why? Any idea?

**Comment by kaishijeng** [comment]
I add more libraries to the Makefile and now compilation is successful.
I can run build/test/test_detect, build/test/test_align and results are OK.
However, when I run build/test/face_test and I got the following message:
caffe is not supported
supported types:  mxnet

Same response when I run build/bin/face_demo:
caffe is not supported
supported types:  mxnet

Any idea?

**Comment by cyberfire** [comment]
I guess that you should enable caffe in config.mk
  CONFIG_CAFFE_MTCNN=n

Or  add "-t" 
build/test/face_test -t mxnet

**Comment by kaishijeng** [comment]
Thanks. It works now. I have firefly 3399 and each frame takes about 650ms
to process
Is this reasonable?

Thanks,

**Comment by cyberfire** [comment]
I don't benchmark on the performance yet. So that I cannot comment your result.

Thanks,

Haitao
